FROM docker:27.3.1-dind

USER root

# Install base software
RUN apk add --no-cache \
      git \
      python3 \
      py3-pip \
      curl \
      wget \
      unzip \
      tar \
      openjdk11 \
      bash \
      ca-certificates \
      && update-ca-certificates

# Install Maven 3.6.3
ENV MAVEN_VERSION=3.6.3
ENV MAVEN_HOME=/opt/maven
ENV PATH=${MAVEN_HOME}/bin:${PATH}

RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    | tar -xz -C /opt && \
    ln -s /opt/apache-maven-${MAVEN_VERSION} ${MAVEN_HOME}

# Install Python modules
RUN pip3 install --break-system-packages ansible docker

# Install Docker Buildx plugin
ENV BUILDX_VERSION=0.18.0
RUN mkdir -p /usr/libexec/docker/cli-plugins && \
    curl -fsSL https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64 \
    -o /usr/libexec/docker/cli-plugins/docker-buildx && \
    chmod +x /usr/libexec/docker/cli-plugins/docker-buildx && \
    chmod +x /usr/local/bin -R
ENV HOME=/root
ENV DOCKER_CONFIG=/root/.docker

ARG ARGOCD_VERSION=v2.12.3

RUN apk add --no-cache curl \
    && curl -sSL -o /usr/local/bin/argocd \
       https://github.com/argoproj/argo-cd/releases/download/${ARGOCD_VERSION}/argocd-linux-amd64 \
    && chmod +x /usr/local/bin/argocd

# Default command starts Docker daemon
CMD ["dockerd-entrypoint.sh"]
