apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-app-service
  name: sample-app-service
spec:
  ports:
  - name: port
    port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    app: sample-app-service
  type: NodePort
status:
  loadBalancer: {}
